vpipe:
  general:
      aligner: "bwa"
      snv_caller: "shorah"

  input:
      reference: ../references/DCV_Cha.fasta
      datadir: ../samples/parental_stock
      read_length: 100
      samples_file: samples_parental_stock.tsv
      paired: true

  snv:
    consensus: false

  shorah:
    time: 140

  output:
      datadir: results/parental_stock_ref_Cha/results_vpipe

      snv: true
      local: true
      global: false
      visualization: true
      diversity: false
      QA: false

output_dir: results/parental_stock_ref_Cha
