vpipe:
  general:
      aligner: "bwa"
      snv_caller: "shorah"

  input:
      reference: ../references/parental_stock.consensus.fasta
      datadir: ../../../../samples/mongelli2022
      read_length: 130
      samples_file: samples_mongelli2022.tsv
      paired: false

  snv:
    consensus: false
    disk_mb: 1250
    mem_mb: 35000
    time_min: 6000
    threads: 64

  output:
      datadir: results/mongelli2022/results_vpipe

      snv: true
      local: true
      global: false
      visualization: true
      diversity: false
      QA: false

output_dir: results/mongelli2022
