vpipe:
  general:
      aligner: "bwa"
      snv_caller: "shorah"

  input:
      reference: resources/references/DCV_EBref.fasta
      datadir: resources/samples/parental_stock
      read_length: 100
      samples_file: samples_parental_stock.tsv
      paired: true

  snv:
    consensus: false

  shorah:
    time: 140

  output:
      datadir: results/results_vpipe

      snv: true
      local: true
      global: false
      visualization: false
      diversity: false
      QA: false
