vpipe:
  general:
      aligner: "bwa"
      snv_caller: "shorah"

  input:
      reference: results/parental_stock/results_vpipe/parental_stock/DCV_PO/references/consensus.bcftools.fasta
      datadir: ../samples/dicer_KO
      read_length: 100
      samples_file: samples_dicer_KO.tsv
      paired: true

  snv:
    consensus: false

  shorah:
    time: 140
      threads: 100

  output:
      datadir: results/dicer_KO/results_vpipe

      snv: true
      local: true
      global: false
      visualization: true
      diversity: false
      QA: false

output_dir: results/dicer_KO
